-- SUPABASE_SETUP.sql — SUPERSEDED. Do not run this file.
--
-- This used to define jobsy_sessions and ask an operator to paste it into the
-- Supabase SQL editor as a one-time manual step. Two things were wrong with
-- that, and both are now fixed elsewhere:
--
-- 1. It was never actually run. Checked 2026-08-31: jobsy_sessions did not
--    exist in the project at all, which is why saving a session reported
--    "Save failed." and had done since the feature shipped. A table the
--    application depends on cannot live in a manual step, because a manual
--    step is a step that gets skipped and nothing notices.
--
-- 2. Its jobsy_sessions had no tenant key. Every client's roster would have
--    landed in one table separated only by a session code that travelled in
--    the URL. Fine for one customer, catastrophic for the second.
--
-- The table now lives in supabase/migrations/0007_partners_users_and_membership.sql
-- with org_id NOT NULL from birth, and migration 0008 puts a row-level security
-- policy on it so membership decides access rather than knowledge of a code.
--
-- SETUP IS NOW: apply the migrations in order.
--
--   supabase/migrations/0001_reference_library.sql
--   ...
--   supabase/migrations/0008_rls_policies.sql
--
-- Then register the first people with tools/manage_users.py — there is no
-- sign-up page, by design. See docs/PLAN-whitelabel-tenancy.md.
--
-- To check the whole series applies and the fence actually holds:
--
--   ./supabase/tests/run.sh
--
-- This file is kept rather than deleted so that anything still pointing at it
-- finds the explanation instead of a 404.
