"""
jobsy/services/pay_equity_export_service.py

Turns a PayGapResult (services.pay_equity_service.analyze_gender_pay_gap) into a
formatted Excel workbook so a structural gender pay-gap run can leave the app as
a shareable report — mirrors services.export_service.ExportService, but for the
band-free Function x Level gap instead of matched titles.

Two entry points:

    to_workbook_bytes(result) -> bytes   (for Streamlit download_button)
    write_workbook(result, path) -> Path (to disk)

Workbook layout ("2.0" -- consolidated onto one page rather than four tabs,
per client feedback on the earlier per-sheet version):
    Summary   headline metrics, notes, a reliable-cohorts mean-pay mini-table
              feeding a Male-vs-Female bar chart, and both representation
              tables (by level, by function) -- all on one sheet, side by side
    Cohorts   every Function x Level cohort with both men and women

The export is a static snapshot of one analysis run, so it holds values rather
than formulas.

Sign convention: PayGapResult's own fields are "positive = men paid more".
This export instead reports "positive = women paid more" -- (vrouw - man) /
man -- to match the NL wetsvoorstel's own definition of "loonkloof", since
that's the wording this report gets checked against. The live Jobsy screen
applies the same flip (see ui/app.py::_render_leveled_gap) so the two never
disagree; see services.pay_equity_service.flip_gap_sign / flip_gap_ci.

Styling is on-brand: header fill is Jobsy's deep purple, and gap values are
colour-coded with the same danger/teal threshold logic as _render_leveled_gap's
on-screen _col(). Colours are literal hex here (not imported from ui/theme.py)
so this module -- pure pandas/openpyxl -- never needs streamlit importable;
keep the two in sync by hand if the Jobsy palette changes.
"""

from __future__ import annotations

from io import BytesIO
from pathlib import Path

import pandas as pd

import logging
logger = logging.getLogger('jobsy')
from services.pay_equity_service import PayGapResult, DIRECTIVE_THRESHOLD_PCT, flip_gap_sign, flip_gap_ci

__all__ = ["PayEquityExportService"]

_GAP_PCT_FMT = '+0.0"%";-0.0"%"'  # values are already 0-100 scale, not 0-1 -- no native '%' format

# Jobsy brand palette -- hex without the '#', as openpyxl wants it.
_PURPLE = "53037F"    # header fill (deep purple; darker than ui/theme.py's on-screen primary,
                       # chosen for print/spreadsheet contrast)
_PINK = "FF73D0"      # accent -- Female chart series
_TEAL = "34B5FF"      # secondary -- on-screen "fine" gap colour
_DANGER = "FF5A7A"    # clay -- on-screen "flagged" gap colour
_DANGER_SOFT = "FDE3E9"
_TEAL_SOFT = "E2F2FF"

_FONT = "Arial"

# ── translation ──────────────────────────────────────────────────────────────
# Two kinds of English text flow into this workbook: (1) fixed labels/headers
# written here in the export layer -- a straight 1:1 dict lookup -- and (2)
# freeform NOTES generated by the analysis engine (services.pay_equity_service),
# some with embedded numbers (e.g. "12 of 67 input row(s)..."). Rather than
# duplicating the engine's note-generation logic in Dutch (a second place
# those sentences could drift out of sync), _translate_note() matches each
# English note against the small, closed set of templates the engine actually
# emits (see analyze_gender_pay_gap / _grade_assignment_gap) and rebuilds the
# Dutch sentence from the SAME extracted numbers. An unrecognised note (e.g.
# a future engine change) falls back to the English original rather than
# silently dropping information from the report.

_LABELS_NL: dict[str, str] = {
    "Metric": "Metriek", "Value": "Waarde",
    "Rows received (before any exclusion)": "Ontvangen rijen (vóór uitsluitingen)",
    "  dropped — missing/zero salary or blank function/level":
        "  uitgesloten — ontbrekend/nul salaris of leeg functie/niveau",
    "Employees in scope": "Medewerkers in scope",
    "Men (M)": "Mannen (M)", "Women (F)": "Vrouwen (V)",
    "Excluded from binary gap (non-binary / unknown gender)":
        "Uitgesloten van binaire loonkloof (non-binair / onbekend geslacht)",
    "Reconciliation: received − dropped = in scope":
        "Aansluiting: ontvangen − uitgesloten = in scope",
    "OK": "OK", "MISMATCH — investigate": "AFWIJKING — onderzoeken",
    "FTE-normalised": "Genormaliseerd naar FTE", "Yes": "Ja", "No": "Nee",
    "Mean gap % — unadjusted (+ = women paid more, per wetsvoorstel (vrouw-man)/man)":
        "Gemiddelde loonkloof % — ongecorrigeerd (+ = vrouwen verdienen meer, "
        "conform wetsvoorstel (vrouw-man)/man)",
    "Median gap % — unadjusted (+ = women paid more)":
        "Mediane loonkloof % — ongecorrigeerd (+ = vrouwen verdienen meer)",
    "Adjusted gap % (controls for function + level; + = women paid more)":
        "Gecorrigeerde loonkloof % (gecontroleerd voor functie + niveau; + = vrouwen verdienen meer)",
    "Adjusted 95% CI — low": "Gecorrigeerd 95%-BI — laag",
    "Adjusted 95% CI — high": "Gecorrigeerd 95%-BI — hoog",
    "Adjusted gap statistically significant": "Gecorrigeerde loonkloof statistisch significant",
    "Grade-assignment gap, in LEVELS not % (does gender predict the level itself, "
    "not just pay within it; + = women sit at a higher level)":
        "Niveau-indelingskloof, in NIVEAUS niet % (voorspelt geslacht het niveau zelf, "
        "niet alleen de beloning binnen dat niveau; + = vrouwen zitten op een hoger niveau)",
    "Grade-assignment 95% CI — low": "Niveau-indelingskloof 95%-BI — laag",
    "Grade-assignment 95% CI — high": "Niveau-indelingskloof 95%-BI — hoog",
    "Grade-assignment gap statistically significant":
        "Niveau-indelingskloof statistisch significant",
    "Cohorts tested (Function x Level, both genders)":
        "Geteste cohorten (Functie x Niveau, beide geslachten)",
    "Cohorts below the n>=5-per-gender reliability threshold (low-n, indicative only)":
        "Cohorten onder de betrouwbaarheidsdrempel van n>=5 per geslacht (laag-n, indicatief)",
    "Levels 100% one gender (no computable gap — absent from Cohorts; "
    "a segregation signal in its own right)":
        "Niveaus 100% één geslacht (geen berekenbare kloof — ontbreekt in Cohorten; "
        "op zichzelf een segregatiesignaal)",
    "None": "Geen",
    "% women overall": "% vrouwen totaal",
    "Function": "Functie", "Level": "Niveau",
    "n Male": "n Man", "n Female": "n Vrouw",
    "Mean M": "Gem. M", "Mean F": "Gem. V",
    "Median M": "Mediaan M", "Median F": "Mediaan V",
    "Mean gap % (+ = women paid more)": "Gemiddelde kloof % (+ = vrouwen verdienen meer)",
    "Median gap % (+ = women paid more)": "Mediane kloof % (+ = vrouwen verdienen meer)",
    "Reliable (n>=5 each)": "Betrouwbaar (n>=5 elk)",
    "% women": "% vrouwen",
    "Reliable cohorts — mean pay by gender (n>=5 each)":
        "Betrouwbare cohorten — gemiddeld loon per geslacht (n>=5 elk)",
    "Notes": "Toelichting", "Function x Level": "Functie x Niveau",
    "No cohort has a reliable (n>=5 each gender) sample -- no chart to show.":
        "Geen enkel cohort heeft een betrouwbare steekproef (n>=5 per geslacht) — geen grafiek beschikbaar.",
    "Mean pay by cohort, Male vs Female (reliable cohorts only)":
        "Gemiddeld loon per cohort, Man vs Vrouw (alleen betrouwbare cohorten)",
    "Salary": "Salaris",
}


def _fmt_cohort_list(items, lang: str) -> str:
    """'F (M, n=13), 4 (M, n=4)' either language -- values are level labels,
    left untranslated since they come straight from the client's own file."""
    return ", ".join(items) if items else _LABELS_NL["None"] if lang == "nl" else "None"


# Closed set of note TEMPLATES the engine (services/pay_equity_service.py)
# actually emits, each as (matcher-prefix, dutch-builder). Matched by prefix
# because every dynamic note starts with fixed wording before the numbers.
def _translate_note(note: str) -> str:
    import re

    if note.startswith("Salary supplied as full-time-equivalent by the source"):
        return ("Salaris door de bron al aangeleverd als fulltime-equivalent — "
                "geen extra FTE-herrekening toegepast.")
    if note.startswith("No FTE column supplied"):
        return ("Geen FTE-kolom aangeleverd — deeltijdsalaris is niet herrekend naar fulltime, "
                "wat (zeker in de Nederlandse context) de loonkloof doorgaans overschat.")
    m = re.match(
        r"EXCLUSIONS: (\d+) of (\d+) input row\(s\) were dropped for a missing/zero salary or a "
        r"blank function/level \((\d+) male, (\d+) female, (\d+) other/unknown\)\.", note)
    if m:
        n_drop, n_in, dm, df_, other = m.groups()
        return (f"UITSLUITINGEN: {n_drop} van de {n_in} aangeleverde rij(en) zijn uitgesloten wegens "
                f"ontbrekend/nul salaris of een leeg functie/niveau-veld ({dm} man, {df_} vrouw, "
                f"{other} overig/onbekend). Elk cijfer in deze analyse betreft alleen de resterende "
                "rijen — sluit deze uitsluitingen aan op de bron voordat een getal als volledig geldt.")
    m = re.match(r"(\d+) row\(s\) with a non-binary/unknown gender are excluded", note)
    if m:
        n = m.group(1)
        return (f"{n} rij(en) met een non-binair/onbekend geslacht zijn uitgesloten van de binaire "
                "loonkloof, maar wel meegeteld in de representatiecijfers.")
    if note.startswith("Level values aren't numeric/ordinal enough"):
        return ("Niveauwaarden zijn niet numeriek/ordinaal genoeg om de niveau-indeling zo te toetsen "
                "(bijv. 1-12 nodig, geen vrije-tekst gradaties).")
    if note.startswith("Not enough rows to test grade assignment"):
        return "Onvoldoende rijen om de niveau-indeling tegen functie (+ dienstjaren) te toetsen."
    if note.startswith("Controls for function only, not tenure"):
        return ("Gecontroleerd voor functie, niet voor dienstjaren — een resterend verschil kan deels "
                "een oprecht dienstjarenverschil weerspiegelen in plaats van scheve indeling. Lever een "
                "kolom met dienstjaren/startdatum aan om dit te versterken.")
    if note.startswith("Grade-assignment model could not be fit"):
        return "Het niveau-indelingsmodel kon niet op deze data worden gefit."
    m = re.match(r"(\d+) level\(s\) are 100% one gender", note)
    if m:
        n = m.group(1)
        return (f"{n} niveau(s) zijn 100% één geslacht en hebben daarom geen berekenbare kloof — deze "
                "verschijnen NIET in de cohortentabel, maar in de lijst 'niveaus met één geslacht'. Een "
                "niveau dat volledig één geslacht is, is op zichzelf een segregatiesignaal; afwezigheid "
                "in de cohortentabel mag niet gelezen worden als afwezigheid van een probleem.")
    m = re.match(r"Cohorts with fewer than (\d+) of either gender", note)
    if m:
        n = m.group(1)
        return (f"Cohorten met minder dan {n} van beide geslachten zijn gemarkeerd als lage steekproef "
                "— behandel hun loonkloof als indicatief.")
    if note.startswith("Adjusted gap controls for function and level only"):
        return ("De gecorrigeerde loonkloof houdt alleen rekening met functie en niveau — niet met "
                "dienstjaren, uren, prestaties of locatie. Een resterende kloof is aanleiding voor "
                "onderzoek, geen bewijs van een ongerechtvaardigde kloof.")
    if note.startswith("The grade-assignment gap tests whether gender predicts"):
        return ("De niveau-indelingskloof toetst of geslacht het niveau zelf voorspelt (een statistisch "
                "signaal uit reeds verzamelde data) — dit vervangt geen volledige functiewaardering "
                "(punten-factorenmethode) op vaardigheden, inspanning, verantwoordelijkheid en "
                "arbeidsomstandigheden, zoals Art. 4 vereist en waarvoor deze tool momenteel geen data "
                "verzamelt. Behandel een significante niveau-indelingskloof als aanleiding om die "
                "bredere evaluatie te laten uitvoeren, niet als bewijs op zichzelf.")
    if note.startswith("Dutch implementing legislation for the EU Pay Transparency Directive"):
        return ("De Nederlandse implementatiewetgeving voor de EU Richtlijn Loontransparantie is nog "
                "niet van kracht (wetsvoorstel bij de Tweede Kamer per mei 2026, beoogd 1 januari 2027 "
                "— later dan de oorspronkelijke EU-deadline van juni 2026, die de Europese Commissie "
                "niet heeft verlengd). Zodra van kracht, is de formele rapportageplicht die de "
                "hersteltermijn van 6 maanden laat ingaan gefaseerd naar omvang: 150+ werknemers "
                "rapporteren voor het eerst op 7 juni 2028 (daarna jaarlijks); 100-149 werknemers voor "
                "het eerst op 7 juni 2031 (elke 3 jaar); onder de 100 werknemers geldt geen "
                "rapportageplicht via dit mechanisme. Beschouw deze analyse als voorlopen op de wet, "
                "niet als een actuele compliancedeadline, tenzij de klant al 150+ medewerkers telt.")
    if note.startswith("Sign convention:"):
        return ("Tekenconventie: de cijfers in dit rapport zijn (vrouw - man) / man, d.w.z. positief = "
                "vrouwen verdienen meer — conform de definitie van 'loonkloof' in het Nederlandse "
                "wetsvoorstel. Het live Jobsy-scherm gebruikt dezelfde conventie.")
    return note  # unrecognised note (e.g. a future engine change) -- keep it visible, in English


def _tr(text: str, lang: str) -> str:
    """Fixed-label lookup. Falls back to the English text if untranslated."""
    return _LABELS_NL.get(text, text) if lang == "nl" else text


class PayEquityExportService:
    """Renders a PayGapResult to a styled workbook. Pass lang="nl" to any
    method (or the constructor) for a fully Dutch-language report -- labels,
    headers, chart titles and the analysis notes are all translated; only
    the client's own data (function/level names, numbers) is untouched."""

    def __init__(self, lang: str = "en"):
        self.lang = lang

    # ------------------------------------------------------------- dataframes
    def summary_to_dataframe(self, r: PayGapResult, lang: str | None = None) -> pd.DataFrame:
        lang = lang or self.lang
        _t = lambda s: _tr(s, lang)
        ci_lo, ci_hi = flip_gap_ci(r.adjusted_ci) or (None, None)
        flagged_label = (f"Cohorten gemarkeerd (|kloof| >= {DIRECTIVE_THRESHOLD_PCT:.0f}%)" if lang == "nl"
                         else f"Cohorts flagged (|gap| >= {DIRECTIVE_THRESHOLD_PCT:.0f}%)")
        reliable_label = ("  ...waarvan betrouwbaar (n >= 5 per geslacht)" if lang == "nl"
                          else "  ...of which reliable (n >= 5 each gender)")
        single_gender_val = (", ".join(f"{lvl} ({g}, n={n})" for lvl, (g, n) in sorted(
                                 r.single_gender_levels.items(), key=lambda kv: str(kv[0])))
                             if r.single_gender_levels else _t("None"))
        rows = [
            (_t("Rows received (before any exclusion)"), r.n_input or r.n),
            (_t("  dropped — missing/zero salary or blank function/level"), r.n_dropped_invalid),
            (_t("Employees in scope"), r.n),
            (_t("Men (M)"), r.n_m),
            (_t("Women (F)"), r.n_f),
            (_t("Excluded from binary gap (non-binary / unknown gender)"), r.n_excluded),
            (_t("Reconciliation: received − dropped = in scope"),
             _t("OK") if (r.n_input or r.n) - r.n_dropped_invalid == r.n else _t("MISMATCH — investigate")),
            (_t("FTE-normalised"), _t("Yes") if r.fte_normalised else _t("No")),
            (None, None),
            (_t("Mean gap % — unadjusted (+ = women paid more, per wetsvoorstel (vrouw-man)/man)"),
             flip_gap_sign(r.mean_gap_pct)),
            (_t("Median gap % — unadjusted (+ = women paid more)"), flip_gap_sign(r.median_gap_pct)),
            (None, None),
            (_t("Adjusted gap % (controls for function + level; + = women paid more)"),
             flip_gap_sign(r.adjusted_gap_pct)),
            (_t("Adjusted 95% CI — low"), ci_lo),
            (_t("Adjusted 95% CI — high"), ci_hi),
            (_t("Adjusted gap statistically significant"),
             None if r.adjusted_significant is None else (_t("Yes") if r.adjusted_significant else _t("No"))),
            (None, None),
            (_t("Grade-assignment gap, in LEVELS not % (does gender predict the level itself, "
                "not just pay within it; + = women sit at a higher level)"),
             flip_gap_sign(r.grade_gap_levels)),
            (_t("Grade-assignment 95% CI — low"), (flip_gap_ci(r.grade_gap_ci) or (None, None))[0]),
            (_t("Grade-assignment 95% CI — high"), (flip_gap_ci(r.grade_gap_ci) or (None, None))[1]),
            (_t("Grade-assignment gap statistically significant"),
             None if r.grade_gap_significant is None else (_t("Yes") if r.grade_gap_significant else _t("No"))),
            (None, None),
            (_t("Cohorts tested (Function x Level, both genders)"), r.n_cohorts_tested),
            (flagged_label, r.n_cohorts_flagged),
            (reliable_label, r.n_cohorts_flagged_reliable),
            (_t("Cohorts below the n>=5-per-gender reliability threshold (low-n, indicative only)"),
             sum(1 for c in r.cohorts if not c.reliable)),
            (_t("Levels 100% one gender (no computable gap — absent from Cohorts; "
                "a segregation signal in its own right)"), single_gender_val),
            (None, None),
            (_t("% women overall"), r.pct_women_overall),
        ]
        return pd.DataFrame(rows, columns=[_t("Metric"), _t("Value")])

    def cohorts_to_dataframe(self, r: PayGapResult, lang: str | None = None) -> pd.DataFrame:
        lang = lang or self.lang
        _t = lambda s: _tr(s, lang)
        flagged_col = (f"Gemarkeerd (>= {DIRECTIVE_THRESHOLD_PCT:.0f}%)" if lang == "nl"
                      else f"Flagged (>= {DIRECTIVE_THRESHOLD_PCT:.0f}%)")
        rows = [{
            _t("Function"): c.function, _t("Level"): c.level,
            _t("n Male"): c.n_m, _t("n Female"): c.n_f,
            _t("Mean M"): c.mean_m, _t("Mean F"): c.mean_f,
            _t("Median M"): c.median_m, _t("Median F"): c.median_f,
            _t("Mean gap % (+ = women paid more)"): flip_gap_sign(c.mean_gap_pct),
            _t("Median gap % (+ = women paid more)"): flip_gap_sign(c.median_gap_pct),
            flagged_col: _t("Yes") if c.flagged else _t("No"),
            _t("Reliable (n>=5 each)"): _t("Yes") if c.reliable else _t("No"),
        } for c in r.cohorts]
        return pd.DataFrame(rows)

    def representation_to_dataframe(self, r: PayGapResult, by: str, lang: str | None = None) -> pd.DataFrame:
        lang = lang or self.lang
        data = r.women_by_level if by == "level" else r.women_by_function
        label = _tr("Level", lang) if by == "level" else _tr("Function", lang)
        pct_label = _tr("% women", lang)
        rows = [{label: k, pct_label: v} for k, v in data.items()]
        return pd.DataFrame(rows, columns=[label, pct_label])

    def notes_list(self, r: PayGapResult, lang: str | None = None) -> list[str]:
        lang = lang or self.lang
        sign_note = ("Sign convention: figures in this report are (vrouw - man) / man, i.e. "
                     "positive = women paid more -- matching the NL wetsvoorstel's definition of "
                     "'loonkloof'. The live Jobsy screen uses the same convention.")
        notes = [sign_note, *r.notes]
        return [_translate_note(n) for n in notes] if lang == "nl" else notes

    # --------------------------------------------------------------- exporters
    def to_workbook_bytes(self, result: PayGapResult, lang: str | None = None) -> bytes:
        lang = lang or self.lang
        summary = self.summary_to_dataframe(result, lang)
        cohorts = self.cohorts_to_dataframe(result, lang)
        summary_sheet = "Samenvatting" if lang == "nl" else "Summary"
        cohorts_sheet = "Cohorten" if lang == "nl" else "Cohorts"

        buffer = BytesIO()
        with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
            # startcol=1 leaves column A as a narrow left margin, matching the rest of the sheet
            summary.to_excel(writer, sheet_name=summary_sheet, index=False, startcol=1)
            if not cohorts.empty:
                cohorts.to_excel(writer, sheet_name=cohorts_sheet, index=False)
            try:
                ws = writer.sheets[summary_sheet]
                self._format_summary_metrics(ws, len(summary), result, lang)
                self._add_dashboard_section(ws, result, dashboard_row=len(summary) + 4, lang=lang)
                if not cohorts.empty:
                    self._format_data_sheet(writer.sheets[cohorts_sheet], cohorts)
            except Exception as exc:  # formatting must never break the export
                logger.warning("Pay-equity workbook formatting skipped: %s", exc)

        logger.info("Exported pay-equity report (lang=%s): n=%d (M=%d, F=%d), %d cohorts.",
                    lang, result.n, result.n_m, result.n_f, result.n_cohorts_tested)
        return buffer.getvalue()

    def write_workbook(self, result: PayGapResult, path: str | Path, lang: str | None = None) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(self.to_workbook_bytes(result, lang))
        return path

    # ---------------------------------------------------------------- styling
    def _gap_color(self, value) -> str:
        """Same threshold logic as the on-screen _col() in ui/app.py::_render_leveled_gap.
        Guards on type, not just `is not None` -- pandas writes a blank Value cell
        (e.g. Adjusted gap % when the regression has too few rows) as '' once it
        shares a mixed-type column with strings like FTE-normalised's 'Yes'/'No',
        not as a true empty cell, so `value` can be '' here rather than None."""
        if not isinstance(value, (int, float)):
            return _TEAL
        return _DANGER if abs(value) >= DIRECTIVE_THRESHOLD_PCT else _TEAL

    def _style_header_cells(self, cells) -> None:
        from openpyxl.styles import Alignment, Font, PatternFill
        font = Font(name=_FONT, bold=True, color="FFFFFF")
        fill = PatternFill("solid", fgColor=_PURPLE)
        center = Alignment(horizontal="center", vertical="center")
        for cell in cells:
            cell.font = font
            cell.fill = fill
            cell.alignment = center

    def _header_row_style(self, ws, row: int = 1):
        self._style_header_cells(ws[row])

    def _format_summary_metrics(self, ws, n_metric_rows: int, r: PayGapResult | None = None,
                                lang: str | None = None) -> None:
        """Metrics live in columns B (Metric) / C (Value); column A is a left margin.
        Label matching checks both English and Dutch wording -- the two label sets
        share no common substring by design, so each check lists both explicitly."""
        from openpyxl.styles import Font
        lang = lang or self.lang
        self._style_header_cells((ws.cell(1, 2), ws.cell(1, 3)))
        ws.freeze_panes = "A2"
        ws.column_dimensions["A"].width = 4.5
        ws.column_dimensions["B"].width = 70
        ws.column_dimensions["C"].width = 16
        # Grade-assignment gap is in LEVELS, not %, and its own threshold is
        # statistical significance (not the 5% pct-gap trigger _gap_color uses),
        # so it gets a distinct colour decision rather than reusing that logic.
        grade_gap_color = _DANGER if (r is not None and r.grade_gap_significant) else _TEAL
        for row in range(2, n_metric_rows + 2):
            label_cell = ws.cell(row=row, column=2)
            label = label_cell.value
            if label is None:
                continue
            label_l = str(label).lower()
            value_cell = ws.cell(row=row, column=3)
            if ("gap %" in label_l or "kloof %" in label_l
                    or "% women" in label_l or "% vrouwen" in label_l):
                value_cell.number_format = _GAP_PCT_FMT
            if str(label).startswith(("Mean gap", "Median gap", "Adjusted gap %",
                                      "Gemiddelde loonkloof", "Gemiddelde kloof",
                                      "Mediane loonkloof", "Mediane kloof", "Gecorrigeerde loonkloof %")):
                value_cell.font = Font(name=_FONT, bold=True, color=self._gap_color(value_cell.value))
            elif str(label).startswith(("Grade-assignment gap, in LEVELS", "Niveau-indelingskloof, in NIVEAUS")):
                value_cell.number_format = '+0.00;-0.00'
                value_cell.font = Font(name=_FONT, bold=True, color=grade_gap_color)

    def _add_dashboard_section(self, ws, r: PayGapResult, dashboard_row: int, lang: str | None = None) -> None:
        """Below the metrics: a title row, then one shared header row for four
        side-by-side blocks -- Notes (B), reliable-cohorts mean-pay mini-table
        feeding a bar chart (E:G), representation by level (I:J), representation
        by function (K:L) -- each sized to its own content."""
        from openpyxl.styles import Font
        lang = lang or self.lang
        _t = lambda s: _tr(s, lang)

        title_cell = ws.cell(dashboard_row, 2, _t("Reliable cohorts — mean pay by gender (n>=5 each)"))
        title_cell.font = Font(name=_FONT, bold=True)

        header_row = dashboard_row + 1
        data_row = header_row + 1

        headers = {2: _t("Notes"), 5: _t("Function x Level"), 6: _t("Mean M"), 7: _t("Mean F"),
                   9: _t("Level"), 10: _t("% women"), 11: _t("Function"), 12: _t("% women")}
        for col, label in headers.items():
            ws.cell(header_row, col, label)
        self._style_header_cells([ws.cell(header_row, col) for col in headers])

        notes = self.notes_list(r, lang)
        for i, note in enumerate(notes):
            ws.cell(data_row + i, 2, note)

        reliable = [c for c in r.cohorts if c.reliable]
        if reliable:
            for i, c in enumerate(reliable):
                row = data_row + i
                ws.cell(row, 5, f"{c.function}-{c.level}")
                ws.cell(row, 6, c.mean_m).number_format = "#,##0"
                ws.cell(row, 7, c.mean_f).number_format = "#,##0"
            self._add_reliable_chart(ws, header_row=header_row, n_reliable=len(reliable), lang=lang)
        else:
            note_cell = ws.cell(data_row, 5,
                _t("No cohort has a reliable (n>=5 each gender) sample -- no chart to show."))
            note_cell.font = Font(name=_FONT, italic=True, color="6B7684")

        by_level = self.representation_to_dataframe(r, "level", lang)
        for i, row in enumerate(by_level.itertuples(index=False)):
            ws.cell(data_row + i, 9, row[0])
            ws.cell(data_row + i, 10, row[1])

        by_function = self.representation_to_dataframe(r, "function", lang)
        for i, row in enumerate(by_function.itertuples(index=False)):
            ws.cell(data_row + i, 11, row[0])
            ws.cell(data_row + i, 12, row[1])

        ws.column_dimensions["D"].width = 3.5
        ws.column_dimensions["E"].width = 15
        ws.column_dimensions["F"].width = 14
        ws.column_dimensions["G"].width = 14
        ws.column_dimensions["H"].width = 3.5
        ws.column_dimensions["I"].width = 9
        ws.column_dimensions["J"].width = 10
        ws.column_dimensions["K"].width = 10
        ws.column_dimensions["L"].width = 10

    def _add_reliable_chart(self, ws, *, header_row: int, n_reliable: int, lang: str | None = None) -> None:
        """Clustered Male-vs-Female bar chart, sourced from the mini-table this
        method assumes is already written at columns E:G starting at header_row,
        anchored near the top of the sheet beside the headline metrics. Sized and
        positioned to match the client's own template (~18 x 10.3cm at D2) so it
        doesn't run down into the dashboard section below."""
        from openpyxl.chart import BarChart, Reference
        from openpyxl.chart.label import DataLabelList
        lang = lang or self.lang

        last_row = header_row + n_reliable
        chart = BarChart()
        chart.type = "col"
        chart.grouping = "clustered"
        chart.title = _tr("Mean pay by cohort, Male vs Female (reliable cohorts only)", lang)
        chart.y_axis.title = _tr("Salary", lang)
        chart.x_axis.title = _tr("Function x Level", lang)
        chart.height, chart.width = 10.3, 18
        chart.legend.position = "b"
        cats = Reference(ws, min_col=5, min_row=header_row + 1, max_row=last_row)
        data = Reference(ws, min_col=6, max_col=7, min_row=header_row, max_row=last_row)
        chart.add_data(data, titles_from_data=True)
        chart.set_categories(cats)
        chart.series[0].graphicalProperties.solidFill = _PURPLE  # Mean M
        chart.series[1].graphicalProperties.solidFill = _PINK    # Mean F
        # Every show* flag left as None (the class default) renders in Excel as
        # "series name, category, value" all concatenated on one label -- huge,
        # overlapping text across the whole plot. Every flag must be explicit.
        chart.dataLabels = DataLabelList()
        chart.dataLabels.showVal = True
        chart.dataLabels.showSerName = False
        chart.dataLabels.showCatName = False
        chart.dataLabels.showLegendKey = False
        chart.dataLabels.showPercent = False
        chart.dataLabels.showBubbleSize = False
        chart.dataLabels.dLblPos = "outEnd"
        chart.dataLabels.numFmt = "#,##0"
        ws.add_chart(chart, "D2")

    def _format_data_sheet(self, ws, df: pd.DataFrame) -> None:
        from openpyxl.styles import Font, PatternFill
        from openpyxl.utils import get_column_letter
        self._header_row_style(ws)
        ws.freeze_panes = "A2"
        if ws.max_row >= 1 and ws.max_column >= 1:
            ws.auto_filter.ref = ws.dimensions
        status_fill = {
            "Yes": PatternFill("solid", fgColor=_DANGER_SOFT), "Ja": PatternFill("solid", fgColor=_DANGER_SOFT),
            "No": PatternFill("solid", fgColor=_TEAL_SOFT), "Nee": PatternFill("solid", fgColor=_TEAL_SOFT),
        }
        for idx, header in enumerate(df.columns, start=1):
            lengths = df[header].fillna("").astype(str).map(len)
            longest = int(lengths.max()) if len(lengths) else 0
            width = min(60, max(len(str(header)) + 2, longest + 2))
            ws.column_dimensions[get_column_letter(idx)].width = width
            header_l = str(header).lower()
            if "gap %" in header_l or "kloof %" in header_l:
                for row in range(2, ws.max_row + 1):
                    cell = ws.cell(row=row, column=idx)
                    cell.number_format = _GAP_PCT_FMT
                    cell.font = Font(name=_FONT, color=self._gap_color(cell.value))
            elif header_l.startswith(("flagged", "gemarkeerd")):
                for row in range(2, ws.max_row + 1):
                    cell = ws.cell(row=row, column=idx)
                    cell.fill = status_fill.get(cell.value, status_fill["No"])
